name: dart_socket_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
# dependencies:
# reflectable: ^4.0.5
# path: ^1.8.0
# dart_persistence_api:
# git:
#   url: https://github.com/DerWolf01/dart-persistence-api.git
#   ref: main

dev_dependencies:
  # dart_persistence_api:
  #   git:
  #     ref: main
  #     url: git@github.com:DerWolf01/dart-persistence-api
      # url: https://github.com/DerWolf01/dart_persistence_api
  lints: ^2.1.0
  test: ^1.24.0 
   # dart_persistence_api:
   #   path: ./dart-persistence-api
dependencies:
  characters: ^1.3.0
  path: ^1.9.0
  reflectable: ^4.0.5
  sqflite_common_ffi: ^2.3.1
